apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infin8-master-pipeline-custom-namespace_update_here
  namespace: argocd
  labels:
    environment: environment_update_here
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: project_name_update_here
  source:
    path: namespace_update_here/applications
    repoURL: 'ssh://git@www.inadev.net:7999/iv/infin8-argocd-manifests.git' #Applications Definition Repository.
    targetRevision: tag_update_here #Release Tag.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=false
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true