apiVersion: v1
kind: Secret
metadata:
  name: workflow-manager-service-secret
  namespace: uat-cee-3
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVlNN1BPUU9DV1VTV1BIMlo= # base64 encoded AWS access key ID
  AWS_SECRET_ACCESS_KEY: ZGdxeXBNQ0UvckxRMFFXUTE0MkFVOU9qWTNvdlVIZm1FMzJTTVhrZw== # base64 encoded AWS secret access key