apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deals-service-namespace_update_here
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    environment: environment_update_here
spec:
  destination:
    namespace: namespace_update_here
    server: https://680171219CEFE3546E17BE7BFDDBE955.gr7.us-east-2.eks.amazonaws.com
  project: project_name_update_here
  source:
    repoURL: ssh://git@www.inadev.net:7999/iv/infin8-argocd-manifests.git #Applications Definition Repository.
    path: namespace_update_here/manifests/deal
    targetRevision: branch_update_here #Release Tag.
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true