apiVersion: batch/v1
kind: CronJob
metadata:
  name: lead-rerouting-cronjob
  namespace: uat-cee-3
spec:
  schedule: "*/10 * * * *"  # Runs every day at 9:30 AM
  suspend: false
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
          creationTimestamp: null
        spec:
          containers:
            - name: lead-rerouting-cronjob
              image: 618187721717.dkr.ecr.us-east-1.amazonaws.com/baseline-repository:linux-basic-tools-ssh-mc
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - |
                  curl --location --request POST 'http://lead-routing-service/api/triggerDealRouteCron'
              resources: {}
              securityContext:
                capabilities: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          restartPolicy: Never
          serviceAccountName: default
          terminationGracePeriodSeconds: 30
