apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infin8-master-pipeline-custom
  namespace: argocd
  labels:
    environment: uat
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: uat-cee-3/applications
    repoURL: 'ssh://git@www.inadev.net:7999/iv/infin8-argocd-manifests.git'
    targetRevision: release/UAT
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=false
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true