apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infin8v2-dealdetail-react-app
  name: infin8v2-dealdetail-react-app
  namespace: 'namespace_update_here'
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infin8v2-dealdetail-react-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: infin8v2-dealdetail-react-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: infin8v2-dealdetail-react-app
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: infin8v2-dealdetail-react-app
                topologyKey: topology.kubernetes.io/zone
      containers:
        - env:            
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: BASE_URL
                  name: infin8v2-config-dealdetail-map
          image: 'repository_name_update_here:image_tag_update_here'
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - '60'
          name: infin8v2-dealdetail-react-app
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 65
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: infin8v2-dealdetail-react-app-hpa
  namespace: 'namespace_update_here'
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: infin8v2-dealdetail-react-app
---
apiVersion: v1
kind: Service
metadata:
  namespace: 'namespace_update_here'
  labels:
    name: infin8v2-dealdetail-react-app-service
  name: infin8v2-dealdetail-react-app-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: infin8v2-dealdetail-react-app
